### ISSUE TITLE
solr灌库json文件读取报错

### ISSUE THREAD

**Issue by phlhx** [baidu/AnyQ#100]
使用sh solr_script/anyq_solr.sh solr_script/sample_docs灌库
显示solr已经成功启动，但是json文件读取有以下错误，是否与python版本有关：
solr[8900] start success!
[{'indexed': True, 'stored': True, 'type': 'text_multi_lang', 'name': 'question'}, {'indexed': False, 'stored': True, 'type': 'string', 'name': 'answer'}]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/data/gpu1/zhuchenxi2/AnyQ_bak/build/solr_script/solr_tools.py", line 117, in set_engine_schema
    _get_error_message(err.read())
  File "/data/gpu1/zhuchenxi2/AnyQ_bak/build/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/data/gpu1/zhuchenxi2/AnyQ_bak/build/solr_script/solr_tools.py", line 219, in clear_documents
    _get_error_message(err.read())
  File "/data/gpu1/zhuchenxi2/AnyQ_bak/build/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data/gpu1/zhuchenxi2/AnyQ_bak/build/solr_script/solr_tools.py", line 140, in thread_upload
    _get_error_message(err.read())
  File "/data/gpu1/zhuchenxi2/AnyQ_bak/build/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by zide05** [comment]
遇到同样问题，把solr_script中anyq_solr.sh的SOLR_PORT=8900改成SOLR_PORT=8902就能够运行了，但是不知道这样修改是否正确？（没有在docker中）

**Comment by phlhx** [comment]
太感谢了，确实改一下就可以了，但是在成功启服务后（./run_server）， 确认网页可以打开了，但是输入IP:8999/anyq?question=需要使用什么账号登录"有以下的报错：不知道你是否遇到过。

I0114 09:48:25.570852 24228 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:需要使用什么账号登录\"
I0114 09:48:25.570852 24228 term_retrieval.cpp:109] RAW: solr_fetch_q=question:需要使用什么账号登录\"
I0114 09:48:25.570852 24228 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0114 09:48:25.570852 24228 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E4%BB%80%E4%B9%88%E8%B4%A6%E5%8F%B7%E7%99%BB%E5%BD%95%5C%22&rows=15&wt=json
W0114 09:48:25.570852 24228 term_retrieval.cpp:147] RAW: RAW_LOG ERROR: The Message was too long!
W0114 09:48:25.570852 24228 term_retrieval.cpp:212] RAW: solr_result_parse failed.
E0114 09:48:25.570852 24228 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0114 09:48:25.570852 24228 anyq_strategy.cpp:69] RAW: retrieval module process error
E0114 09:48:25.570852 24228 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

**Comment by zide05** [comment]
刚刚那个问题估计是服务器的8900端口有占用，换一个别的就成，这个问题我也遇到了，卡在这里

**Comment by phlhx** [comment]
感觉预处理都很顺利，但是最后来一个"message was too long"，而且就算把question换成“账号”这两个字，还是too long...等待好心人的解答。

**Comment by zide05** [comment]
你改一下build中example/conf/retrieval.conf中的端口search_port，改成之前在solr_script中anyq_solr.sh的SOLR_PORT设定的端口号试试看

**Comment by phlhx** [comment]
OK了，谢大佬帮助
