### ISSUE TITLE
Error when running solr demo

### ISSUE THREAD

**Issue by mazzzystar** [baidu/AnyQ#108]
Thanks for your work.

I tried command in `demo` until:
```
>>>$ cp ../tools/solr -rp solr_script
MacBook-Pro:demo usr$ cp ../tools/solr -rp solr_script
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```
So I changed this step to:
```
cp -r ../tool/solr .
mv solr solr_script
```
Hope I'm not doing wrong.

Then I run:
```
>>>$ sh solr_script/anyq_solr.sh solr_script/sample_docs
faq-file trans done
appending output to nohup.out
solr[8900] start success!
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 18, in <module>
    import solr_tools
  File "/Users/usr/Documents/QA/AnyQ/demo/solr_script/solr_tools.py", line 55
    print _make_smart_hint(HINT_TYPE_REQ_ERR, errmsg)
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 18, in <module>
    import solr_tools
  File "/Users/usr/Documents/QA/AnyQ/demo/solr_script/solr_tools.py", line 55
    print _make_smart_hint(HINT_TYPE_REQ_ERR, errmsg)
                         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 18, in <module>
    import solr_tools
  File "/Users/usr/Documents/QA/AnyQ/demo/solr_script/solr_tools.py", line 55
    print _make_smart_hint(HINT_TYPE_REQ_ERR, errmsg)
                         ^
SyntaxError: invalid syntax
upload file error
```

**Comment by zhangyanbo2007** [comment]
me too!

**Comment by ZhangZoffy** [comment]
我也遇到了，咋解决的啊？

**Comment by stormbirds** [comment]
这是因为solr_tools.py的写法是python2版本的，你的python版本是3，要么改写solr_tools.py文件的print和urllib2，要么更改你的python版本为2的
