### ISSUE TITLE
train.sh和predict.sh跑不了

### ISSUE THREAD

**Issue by luotao1** [baidu/AnyQ#112]
- 直接运行，报错
```
cd AnyQ/tools/simnet
sh predict.sh
predict.sh: line 11: $1: unbound variable
sh train.sh
train.sh: line 11: $1: unbound variable
```
需要删去两个sh脚本的前三行。
- README里两处写错了：https://github.com/baidu/AnyQ/blob/master/tools/simnet/train/tf/README.md
`examples/cnn_pointwise.json`都应该为`examples/cnn-pointwise.json`
- 运行tensorflow脚本，报错
```
sh train.sh tensorflow
convert train data
convert test data
convert data finish
WARNING:tensorflow:From /home/luotao/AnyQ/tools/simnet/train/tf/utils/datafeeds.py:68: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/luotao/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:276: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/luotao/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:188: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From /home/luotao/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:197: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/luotao/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:197: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/luotao/AnyQ/tools/simnet/train/tf/utils/datafeeds.py:69: __init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TFRecordDataset`.
WARNING:tensorflow:From /home/luotao/AnyQ/tools/simnet/train/tf/utils/datafeeds.py:42: shuffle_batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.shuffle(min_after_dequeue).batch(batch_size)`.
WARNING:tensorflow:From /home/luotao/AnyQ/tools/simnet/train/tf/layers/tf_layers.py:76: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-02-19 15:49:10.630257: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-02-19 15:49:11.385037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-19 15:49:11.387993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:00:0a.0
totalMemory: 15.78GiB freeMemory: 15.37GiB
2019-02-19 15:49:11.388198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-02-19 15:49:11.986994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-19 15:49:11.987178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-02-19 15:49:11.987226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-02-19 15:49:11.987665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14874 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:0a.0, compute capability: 7.0)
WARNING:tensorflow:From /home/luotao/AnyQ/tools/simnet/train/tf/utils/controler.py:89: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
save model epoch1, used time: 1
2019-02-19 15:49:13.851274: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: model/pairwise; No such file or directory
Traceback (most recent call last):
  File "tf_simnet.py", line 135, in <module>
    train(config)
  File "tf_simnet.py", line 84, in train
    controler.run_trainer(loss, optimizer, conf_dict)
  File "/home/luotao/AnyQ/tools/simnet/train/tf/utils/controler.py", line 107, in run_trainer
    "%s/%s.epoch%d" % (model_path, model_file, epoch_num))
  File "/home/luotao/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1458, in save
    raise exc
ValueError: Parent directory of model/pairwise/lstm.epoch1 doesn't exist, can't save.
```

**Comment by oyjxer** [comment]
"cd AnyQ/tools/simnet
sh predict.sh
predict.sh: line 11: $1: unbound variable
sh train.sh
train.sh: line 11: $1: unbound variable"
需要跟选择使用的深度学习平台
例如sh train.sh paddle

**Comment by luotao1** [comment]
@oyjxer 去掉前三行后，会提示选择深度学习平台。
```
$ sh train.sh
illegal platform
Usage:
sh train.sh [paddle/tensorflow]
```
因此，不应该出现`train.sh: line 11: $1: unbound variable"`这个错误

**Comment by yinweichong** [comment]
```
ValueError: Parent directory of model/pairwise/lstm.epoch1 doesn't exist, can't save.
```

model目录不存在, mkdir model
