### ISSUE TITLE
docker环境内 solr[8900] start failed!

### ISSUE THREAD

**Issue by lsyin** [baidu/AnyQ#122]
hi，我在官方给的docker环境内运行sh solr_script/anyq_solr.sh solr_script/sample_docs命令时运行错误，系统显示solr启动失败。我的JDK版本是java version "1.8.0_171"
以下是错误信息：
`faq-file trans done
nohup: appending output to 'nohup.out'
curl: (7) Failed to connect to localhost port 8900: Connection refused
solr[8900] start failed!
[{'indexed': True, 'stored': True, 'type': 'text_multi_lang', 'name': 'question'}, {'indexed': False, 'stored': True, 'type': 'string', 'name': 'answer'}]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/workspace/AnyQ/build/solr_script/solr_tools.py", line 114, in set_engine_schema
    response = urllib2.urlopen(req, json.dumps(schema_config, ensure_ascii=False))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>`
nohup.out跟logs/solr.log 日志里均无错误信息，求帮忙分析下是什么原因造成的，感谢

**Comment by oyjxer** [comment]
参看一下8900端口是否被占用

**Comment by lsyin** [comment]
没有被占用，换了其他端口同样失败。

**Comment by lsyin** [comment]
已解决，solar_deploy里sleep的时间太短，改为60s就可以看到solar start sucess了。
