### ISSUE TITLE
solr编译时出错

### ISSUE THREAD

**Issue by liuyaqingdajie** [baidu/AnyQ#134]
运行这句sh solr_script/anyq_solr.sh solr_script/sample_docs时，报错
faq-file trans done
nohup: 把输出追加到"nohup.out"
solr_script/solr_deply.sh: 行 17:  1046 已放弃               nohup java -DSTOP.PORT=$((solr_port+1)) -DSTOP.KEY=$SOLR_STOP_KEY -Djetty.port=$solr_port -Dsolr.solr.home=${solr_home}/example/solr/ -Djetty.home=${solr_home}/example/ -jar ${solr_home}/example/start.jar
curl: (7) Failed to connect to ::1: 网络不可达
solr[8900] start failed!
java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at org.eclipse.jetty.start.Main.stop(Main.java:1061)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:189)
	at org.eclipse.jetty.start.Main.main(Main.java:94)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
[{'indexed': True, 'stored': True, 'type': 'text_multi_lang', 'name': 'question'}, {'indexed': False, 'stored': True, 'type': 'string', 'name': 'answer'}]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/liuyajie01/AnyQ/build/solr_script/solr_tools.py", line 114, in set_engine_schema
    response = urllib2.urlopen(req, json.dumps(schema_config, ensure_ascii=False))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/liuyajie01/AnyQ/build/solr_script/solr_tools.py", line 216, in clear_documents
    response = urllib2.urlopen(req, urllib.urlencode(params))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/liuyajie01/AnyQ/build/solr_script/solr_tools.py", line 134, in thread_upload
    response = urllib2.urlopen(req, binary_data)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

upload file success

**Comment by liuyaqingdajie** [comment]
然后在运行./run_server
web访问
http://10.146.76.3:8999/anyq?question=python，报错如下
I0409 09:58:31.408202  1203 utils.cpp:590] RAW: in json_to_analysis_item, query:python
I0409 09:58:31.408202  1203 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
I0409 09:58:31.408202  1203 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
I0409 09:58:31.408202  1203 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
I0409 09:58:31.408202  1203 utils.cpp:609] RAW: query:python
I0409 09:58:31.408202  1203 utils.cpp:611] RAW: tokens_basic size is 0
I0409 09:58:31.408202  1203 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
I0409 09:58:31.408202  1203 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
I0409 09:58:31.408202  1203 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
I0409 09:58:31.408202  1203 utils.cpp:609] RAW: query:python
I0409 09:58:31.408202  1203 utils.cpp:611] RAW: tokens_basic size is 1
I0409 09:58:31.408202  1203 utils.cpp:614] RAW: tokens_basic	buffer:python	length:6    offset:0	analysis_term_weight:1.000000
I0409 09:58:31.408202  1203 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:python
I0409 09:58:31.408202  1203 term_retrieval.cpp:109] RAW: solr_fetch_q=question:python
I0409 09:58:31.408202  1203 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0409 09:58:31.408202  1203 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3Apython&rows=15&wt=json
W0409 09:58:31.408202  1203 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
W0409 09:58:31.408202  1203 term_retrieval.cpp:205] RAW: solr_request failed.
E0409 09:58:31.408202  1203 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0409 09:58:31.408202  1203 anyq_strategy.cpp:69] RAW: retrieval module process error
E0409 09:58:31.408202  1203 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

**Comment by liuyaqingdajie** [comment]
然后在运行./run_server
web访问
http://IP:8999/anyq?question=python，报错如下
I0409 09:58:31.408202 1203 utils.cpp:590] RAW: in json_to_analysis_item, query:python
I0409 09:58:31.408202 1203 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
I0409 09:58:31.408202 1203 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
I0409 09:58:31.408202 1203 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
I0409 09:58:31.408202 1203 utils.cpp:609] RAW: query:python
I0409 09:58:31.408202 1203 utils.cpp:611] RAW: tokens_basic size is 0
I0409 09:58:31.408202 1203 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
I0409 09:58:31.408202 1203 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
I0409 09:58:31.408202 1203 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
I0409 09:58:31.408202 1203 utils.cpp:609] RAW: query:python
I0409 09:58:31.408202 1203 utils.cpp:611] RAW: tokens_basic size is 1
I0409 09:58:31.408202 1203 utils.cpp:614] RAW: tokens_basic	buffer:python	length:6 offset:0 analysis_term_weight:1.000000
I0409 09:58:31.408202 1203 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:python
I0409 09:58:31.408202 1203 term_retrieval.cpp:109] RAW: solr_fetch_q=question:python
I0409 09:58:31.408202 1203 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0409 09:58:31.408202 1203 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3Apython&rows=15&wt=json
W0409 09:58:31.408202 1203 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
W0409 09:58:31.408202 1203 term_retrieval.cpp:205] RAW: solr_request failed.
E0409 09:58:31.408202 1203 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0409 09:58:31.408202 1203 anyq_strategy.cpp:69] RAW: retrieval module process error
E0409 09:58:31.408202 1203 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

**Comment by smile901122** [comment]
> 然后在运行./run_server
> web访问
> [http://IP:8999/anyq?question=python，报错如下](http://IP:8999/anyq?question=python%EF%BC%8C%E6%8A%A5%E9%94%99%E5%A6%82%E4%B8%8B)
> I0409 09:58:31.408202 1203 utils.cpp:590] RAW: in json_to_analysis_item, query:python
> I0409 09:58:31.408202 1203 utils.cpp:594] RAW: in json_to_analysis_item, type:(null)
> I0409 09:58:31.408202 1203 analysis_strategy.cpp:115] RAW: analysis_analysis size: 1
> I0409 09:58:31.408202 1203 analysis_strategy.cpp:130] RAW: before use analysis strategy's analysis_result
> I0409 09:58:31.408202 1203 utils.cpp:609] RAW: query:python
> I0409 09:58:31.408202 1203 utils.cpp:611] RAW: tokens_basic size is 0
> I0409 09:58:31.408202 1203 analysis_strategy.cpp:148] RAW: method_process method_wordseg start
> I0409 09:58:31.408202 1203 analysis_strategy.cpp:154] RAW: method_process method_wordseg sucess
> I0409 09:58:31.408202 1203 analysis_strategy.cpp:163] RAW: after use analysis strategy's analysis_result
> I0409 09:58:31.408202 1203 utils.cpp:609] RAW: query:python
> I0409 09:58:31.408202 1203 utils.cpp:611] RAW: tokens_basic size is 1
> I0409 09:58:31.408202 1203 utils.cpp:614] RAW: tokens_basic	buffer:python	length:6 offset:0 analysis_term_weight:1.000000
> I0409 09:58:31.408202 1203 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:python
> I0409 09:58:31.408202 1203 term_retrieval.cpp:109] RAW: solr_fetch_q=question:python
> I0409 09:58:31.408202 1203 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
> I0409 09:58:31.408202 1203 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3Apython&rows=15&wt=json
> W0409 09:58:31.408202 1203 http_client.cpp:94] RAW: curl_easy_perform Failed[Couldn't connect to server];
> W0409 09:58:31.408202 1203 term_retrieval.cpp:205] RAW: solr_request failed.
> E0409 09:58:31.408202 1203 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
> E0409 09:58:31.408202 1203 anyq_strategy.cpp:69] RAW: retrieval module process error
> E0409 09:58:31.408202 1203 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

我也报这个错`curl_easy_perform Failed[Couldn't connect to server];`，请问你知道是什么原因导致的吗？

**Comment by zhangyanbo2007** [comment]
一起讨论下anyQ,15821444815加我微信吧！

**Comment by yinweichong** [comment]
solr启动时，会通过curl "http://localhost:$solr_port/solr"验证是否启动成功，你的环境里localhost没有设置，可修改/etc/hosts

**Comment by zhangsirf** [comment]
你好   你是怎么解决的这问题啊

**Comment by RiceLiuGit** [comment]
我遇到了同样的问题，请问这个问题怎么解决，我用的是windows7系统

**Comment by RiceLiuGit** [comment]
我错误的log和上面几乎一样，请问这个怎么解决：
 cadcc7b926bd /home/AnyQ_build/build {master} sh solr_script/anyq_solr.sh solr_script/sample_docs
faq-file trans done
nohup: appending output to 'nohup.out'
solr_script/solr_deply.sh: line 17:  1217 Aborted                 (core dumped) nohup java -DSTOP.PORT=$((solr_port+1)) -DSTOP.KEY=$SOLR_STOP_KEY -Djetty.port=$solr_port -Dsolr.solr.home=${solr_home}/example/solr/ -Djetty.home=${solr_home}/example/ -jar $
curl: (7) Failed to connect to localhost port 8900: Connection refused
solr[8900] start failed!
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:244)
        at org.eclipse.jetty.start.Main.stop(Main.java:1061)
        at org.eclipse.jetty.start.Main.processCommandLine(Main.java:189)
        at org.eclipse.jetty.start.Main.main(Main.java:94)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
[{'indexed': True, 'stored': True, 'type': 'text_multi_lang', 'name': 'question'}, {'indexed': False, 'stored': True, 'type': 'string', 'name': 'answer'}]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/home/AnyQ_build/build/solr_script/solr_tools.py", line 114, in set_engine_schema
    response = urllib2.urlopen(req, json.dumps(schema_config, ensure_ascii=False))
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/AnyQ_build/build/solr_script/solr_tools.py", line 216, in clear_documents
    response = urllib2.urlopen(req, urllib.urlencode(params))
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python2.7.15/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/python2.7.15/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/AnyQ_build/build/solr_script/solr_tools.py", line 134, in thread_upload
    response = urllib2.urlopen(req, binary_data)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python2.7.15/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 99] Cannot assign requested address>

upload file success
 cadcc7b926bd /home/AnyQ_build/build {master} ps f -ef | grep solr
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
root      1262   401  0 01:41 pts/4    S+     0:00  \_ grep solr
 cadcc7b926bd /home/AnyQ_build/build {master}
@yinweichong @liuyaqingdajie @zhangyanbo2007 @zhangsirf

**Comment by RiceLiuGit** [comment]
我的问题和libpaddle_fluid.so错误有关，参考这个文章https://zhuanlan.zhihu.com/p/73590442解决了问题，感谢文章作者，感谢大家。
问题3：启动solr时候会报错带有libpaddle_fluid.so错误
答案:将AnyQ/build/third_party/lib下的libpaddle_fluid.so拷贝到AnyQ/build/solr-4.10.3-anyq/example/solr-webapp/webapp/WEB-INF/lib下替换已有
将AnyQ/build/solr-4.10.3-anyq/example/solr-webapp下的webapp文件夹拷贝到/tmp/AnyQ/build/solr-4.10.3-anyq/example/webapps下后，将webapp更名为solr
