### ISSUE TITLE
solr 出错

### ISSUE THREAD

**Issue by Rbinnnn** [baidu/AnyQ#180]
[rbin@localhost build]$ sudo sh solr_script/anyq_solr.sh solr_script/sample_docs
faq-file trans done
nohup: 把输出追加到"nohup.out"
solr[8900] start success!
[{'indexed': True, 'stored': True, 'type': 'text_multi_lang', 'name': 'question'}, {'indexed': False, 'stored': True, 'type': 'string', 'name': 'answer'}]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/home/rbin/AnyQ-master/build/solr_script/solr_tools.py", line 117, in set_engine_schema
    _get_error_message(err.read())
  File "/home/rbin/AnyQ-master/build/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/rbin/AnyQ-master/build/solr_script/solr_tools.py", line 219, in clear_documents
    _get_error_message(err.read())
  File "/home/rbin/AnyQ-master/build/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: **No JSON object could be decoded**
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rbin/AnyQ-master/build/solr_script/solr_tools.py", line 140, in thread_upload
    _get_error_message(err.read())
  File "/home/rbin/AnyQ-master/build/solr_script/solr_tools.py", line 53, in _get_error_message
    respond_dict = json.loads(respond_str.strip())
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: **No JSON object could be decoded**

upload file success

如果之后强行启动./run_sever的话，询问问题都会出现以下情况
I0726 22:44:18.192005 29346 utils.cpp:609] RAW: query:百度帐号
I0726 22:44:18.192005 29346 utils.cpp:611] RAW: tokens_basic size is 2
I0726 22:44:18.192005 29346 utils.cpp:614] RAW: tokens_basic	buffer:百度	length:6	offset:0	analysis_term_weight:0.500000
I0726 22:44:18.192005 29346 utils.cpp:614] RAW: tokens_basic	buffer:帐号	length:6	offset:6	analysis_term_weight:0.500000
I0726 22:44:18.192005 29346 equal_solr_q_builder.cpp:48] RAW: equal solr_fetch_q=question:百度帐号
I0726 22:44:18.192005 29346 term_retrieval.cpp:109] RAW: solr_fetch_q=question:百度帐号
I0726 22:44:18.192005 29346 term_retrieval.cpp:119] RAW: url = http://127.0.0.1:8900/solr/collection1/select
I0726 22:44:18.192005 29346 http_client.cpp:84] RAW: para_url: fl=id,question,answer&q=question%3A%E7%99%BE%E5%BA%A6%E5%B8%90%E5%8F%B7&rows=15&wt=json
W0726 22:44:18.192005 29346 term_retrieval.cpp:147] RAW: RAW_LOG ERROR: **The Message was too long!**
W0726 22:44:18.192005 29346 term_retrieval.cpp:212] RAW: solr_result_parse failed.
E0726 22:44:18.192005 29346 retrieval_strategy.cpp:122] RAW: plugin term_recall_1 retrieval error
E0726 22:44:18.192005 29346 anyq_strategy.cpp:69] RAW: retrieval module process error
E0726 22:44:18.192005 29346 http_service_impl.cpp:133] RAW: anyq run_strategy failed!

不知道会不会是jdk的问题
[rbin@localhost build]$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

请求大神答疑解惑

**Comment by lullaby-afa** [comment]
请问这个问题解决了吗
