### ISSUE TITLE
部署 anyq 报错?

### ISSUE THREAD

**Issue by zhangsirf** [baidu/AnyQ#206]
环境:ubuntu 16.04
配置:cmake-3.2.2
         jdk1.8.0_171
         g++ 5.4.0
         .......
本机 docker 已编译好,上传服务器报错>

root@ubuntu:~/AnyQ/build# ./run_server 

root@ubuntu:~/AnyQ/build# sh solr_script/anyq_solr.sh solr_script/sample_docs
faq-file trans done
nohup: appending output to 'nohup.out'
solr_script/solr_deply.sh: line 17:  2782 Aborted                 (core dumped) nohup java -DSTOP.PORT=$((solr_port+1)) -DSTOP.KEY=$SOLR_STOP_KEY -Djetty.port=$solr_port -Dsolr.solr.home=${solr_home}/example/solr/ -Djetty.home=${solr_home}/example/ -jar ${solr_home}/example/start.jar
curl: (7) Failed to connect to localhost port 8900: Connection refused
solr[8900] start failed!
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:244)
        at org.eclipse.jetty.start.Main.stop(Main.java:1061)
        at org.eclipse.jetty.start.Main.processCommandLine(Main.java:189)
        at org.eclipse.jetty.start.Main.main(Main.java:94)

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information
[{'indexed': True, 'stored': True, 'type': 'text_multi_lang', 'name': 'question'}, {'indexed': False, 'stored': True, 'type': 'string', 'name': 'answer'}]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/root/AnyQ/build/solr_script/solr_tools.py", line 114, in set_engine_schema
    response = urllib2.urlopen(req, json.dumps(schema_config, ensure_ascii=False))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/root/AnyQ/build/solr_script/solr_tools.py", line 216, in clear_documents
    response = urllib2.urlopen(req, urllib.urlencode(params))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/AnyQ/build/solr_script/solr_tools.py", line 134, in thread_upload
    response = urllib2.urlopen(req, binary_data)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>

upload file success

求解~

**Comment by liumenggit** [comment]
docker容器 也一样报错

**Comment by lullaby-afa** [comment]
请问解决了吗 遇到了一样的问题~
