### ISSUE TITLE
启动solr的demo出现错误

### ISSUE THREAD

**Issue by Xuanfang1121** [baidu/AnyQ#223]
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 24, in <module>
    solr_tools.set_engine_schema(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "/home/xf/tensorflow-python2/AnyQ/build/solr_script/solr_tools.py", line 114, in set_engine_schema
    response = urllib2.urlopen(req, json.dumps(schema_config, ensure_ascii=False))
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "solr_script/solr_api.py", line 30, in <module>
    solr_tools.clear_documents(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/xf/tensorflow-python2/AnyQ/build/solr_script/solr_tools.py", line 216, in clear_documents
    response = urllib2.urlopen(req, urllib.urlencode(params))
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xf/tensorflow-python2/AnyQ/build/solr_script/solr_tools.py", line 134, in thread_upload
    response = urllib2.urlopen(req, binary_data)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/home/xf/anaconda3/envs/tensorflowgpu07/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
求大神指教，这个错误怎么解决

**Comment by Xuanfang1121** [comment]
可能是python路径不对
