### ISSUE TITLE
训练SimNet时报错

### ISSUE THREAD

**Issue by LongQi** [baidu/AnyQ#32]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, corrupted record at 0
         [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](TFRecordReaderV2, input_producer)]]
INFO:tensorflow:model/pointwise/lstm.final is not in all_model_checkpoint_paths. Manually adding it.
Traceback (most recent call last):
  File "tf_simnet.py", line 135, in <module>
    train(config)
  File "tf_simnet.py", line 84, in train
    controler.run_trainer(loss, optimizer, conf_dict)
  File "/root/workspace/zlong/nlp/anyq/AnyQ/tools/simnet/train/tf/utils/controler.py", line 115, in run_trainer
    coord.join(read_thread)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1249, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
         [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](TFRecordReaderV2, input_producer)]]

**Comment by oyjxer** [comment]
是否进行了数据转化
